### ISSUE TITLE
[Issue]: Package installation error 

### ISSUE THREAD

**Issue by aliefink** [shawnrhoads/pyEM#2]
### Description

Cannot pip install pyEM package due to the following error: 
```
Cloning https://github.com/shawnrhoads/pyEM.git to /tmp/pip-req-build-oywope9g
  Running command git clone --quiet https://github.com/shawnrhoads/pyEM.git /tmp/pip-req-build-oywope9g
  Resolved https://github.com/shawnrhoads/pyEM.git to commit aa4eba1f766f4c362a9645deadd3064166428b79
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-oywope9g/setup.py", line 2, in <module>
          import requests
      ModuleNotFoundError: No module named 'requests'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by shawnrhoads** [comment]
Try installing `requests` either via a new environment:
```
conda create --name emfit pip requests python=3.7.10
conda activate emfit
pip install git+https://github.com/shawnrhoads/pyEM.git 
```

or in your current environment:
```
pip install requests
pip install git+https://github.com/shawnrhoads/pyEM.git 
```

**Comment by shawnrhoads** [comment]
I removed `requests` requirement for installation (4a00d41), so this should no longer be an issue. Thanks for flagging!
